"""
ATM Sentinel — Score Fusion Module
Generated by training/09_score_fusion.py. Do not edit manually.
Import and call fuse() from the inference pipeline.
"""

import json
from pathlib import Path

LEVELS    = ['NONE', 'LOW', 'MEDIUM', 'HIGH']
LEVEL_INT = {l: i for i, l in enumerate(LEVELS)}

_THRESHOLDS_PATH = Path(__file__).resolve().parent.parent / "data" / "thresholds.json"
_cached_thresholds = None

def _load_thresholds() -> dict:
    global _cached_thresholds
    if _cached_thresholds is None:
        _cached_thresholds = json.loads(_THRESHOLDS_PATH.read_text())
    return _cached_thresholds

def _lvl(s: str) -> int:
    return LEVEL_INT.get(s, 0)

def _str(i: int) -> str:
    return LEVELS[max(0, min(3, i))]

def fuse(
    ae_error:    float,
    yolo_dets:   list,          # [{class_idx:int, conf:float}, ...]
    cluster_id:  int,
    loiter_sec:  float = 0.0,
    thresholds:  dict  = None,
) -> dict:
    """
    Combine autoencoder, YOLO, and behaviour signals into one alert.

    Returns dict:
      {
        "alert":        "HIGH"|"MEDIUM"|"LOW"|"NONE",
        "ae_level":     str,
        "yolo_level":   str,
        "beh_level":    str,
        "loiter_bump":  bool,
        "top_det":      {class_name, conf, risk} or None,
        "ae_error":     float,
      }
    """
    if thresholds is None:
        thresholds = _load_thresholds()

    ae_thr   = thresholds["autoencoder"]
    yolo_cfg = thresholds["yolo"]
    beh_cfg  = thresholds["behaviour"]

    # ── Signal 1: autoencoder level ───────────────────────────────────────────
    if ae_error >= ae_thr["high"]:
        ae_level = "HIGH"
    elif ae_error >= ae_thr["medium"]:
        ae_level = "MEDIUM"
    elif ae_error >= ae_thr["low"]:
        ae_level = "LOW"
    else:
        ae_level = "NONE"

    # ── Signal 2: Tool detection level (finetuned YOLOv11n) ────────────────────
    # Detects: crowbar (0), hammer (1), screwdriver (2), drill (3), angle_grinder (4)
    yolo_level = "NONE"
    top_det    = None

    # All 5 finetuned tools are HIGH risk (dangerous tools for ATM break-in)
    class_risk  = {
        "0": "HIGH",  # crowbar
        "1": "HIGH",  # hammer
        "2": "HIGH",  # screwdriver
        "3": "HIGH",  # drill
        "4": "HIGH",  # angle_grinder
    }
    class_names = [
        "crowbar",
        "hammer",
        "screwdriver",
        "drill",
        "angle_grinder"
    ]
    min_conf = {
        "HIGH": 0.75,  # threshold for finetuned tool detection
        "MEDIUM": 0.75,
        "LOW": 0.75,
    }

    # Sort detections by confidence (all are HIGH risk)
    sorted_dets = sorted(yolo_dets, key=lambda d: d["conf"], reverse=True)

    for det in sorted_dets:
        cls_idx = str(det["class_idx"])
        conf    = float(det["conf"])
        risk    = class_risk.get(cls_idx, "NONE")
        if conf >= min_conf.get(risk, 0.75):
            if _lvl(risk) > _lvl(yolo_level):
                yolo_level = risk
                top_det = {
                    "class_name": class_names[int(cls_idx)] if int(cls_idx) < len(class_names) else "unknown",
                    "conf":       round(conf, 3),
                    "risk":       risk,
                }
            break   # take only the top confirmed detection

    # ── Signal 3: behaviour level ─────────────────────────────────────────────
    cluster_risk = beh_cfg.get("cluster_risk", {})
    beh_level    = cluster_risk.get(str(cluster_id), cluster_risk.get(cluster_id, "NONE"))

    # ── Loitering bump ────────────────────────────────────────────────────────
    loiter_bump  = loiter_sec >= thresholds["fusion_rules"]["loitering_seconds"]

    # ── Rule tree ─────────────────────────────────────────────────────────────
    # An alert is only raised when a known threat object is detected by YOLO
    # OR when a person has been loitering for too long.
    # Pure autoencoder / behaviour anomalies alone are suppressed to avoid
    # false alarms on camera noise.

    ae  = _lvl(ae_level)
    yo  = _lvl(yolo_level)
    beh = _lvl(beh_level)
    H, M, L = _lvl("HIGH"), _lvl("MEDIUM"), _lvl("LOW")

    object_detected = yo > 0   # at least one known threat object found

    if object_detected and (
        (yo >= H and (ae >= H or beh >= H))
        or (yo >= H and ae >= M and beh >= M)
    ):
        alert = "HIGH"

    elif object_detected and (
        yo >= H
        or (yo >= M and (ae >= M or beh >= M))
    ):
        alert = "MEDIUM"

    elif object_detected or loiter_bump:
        alert = "LOW"

    else:
        alert = "NONE"

    return {
        "alert":       alert,
        "ae_level":    ae_level,
        "yolo_level":  yolo_level,
        "beh_level":   beh_level,
        "loiter_bump": loiter_bump,
        "top_det":     top_det,
        "ae_error":    round(ae_error, 6),
    }

